# Generated by Django 3.2.9 on 2021-12-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(null=True, upload_to='event_img'),
        ),
        migrations.AlterField(
            model_name='event',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
